/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        display: ['var(--font-display)', '"Clash Display"', 'Satoshi', 'system-ui', 'sans-serif'],
        sans: ['var(--font-body)', 'Satoshi', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        ink: {
          900: "#060611",
          850: "#0a0a16",
          800: "#0d0e1c",
          700: "#121327",
          600: "#1a1c33",
        },
        paper: {
          DEFAULT: "#f7f8fb",
          warm: "#fbfaf7",
          line: "#e7e9f0",
        },
        brand: {
          red: "#ff0800",
          "red-deep": "#940500",
          blue: "#5283ff",
          "blue-deep": "#304c94",
          violet: "#7c3aed",
        },
        red: {
          primary: "#DC2626",
          dark: "#991B1B",
          light: "#FCA5A5",
          50: "#FEF2F2",
          100: "#FEE2E2",
          200: "#FECACA",
          300: "#FCA5A5",
          400: "#F87171",
          500: "#EF4444",
          600: "#DC2626",
          700: "#B91C1C",
          800: "#991B1B",
          900: "#7F1D1D",
        },
        blue: {
          primary: "#2563EB",
          dark: "#1E3A8A",
          light: "#93C5FD",
          50: "#EFF6FF",
          100: "#DBEAFE",
          200: "#BFDBFE",
          300: "#93C5FD",
          400: "#60A5FA",
          500: "#3B82F6",
          600: "#2563EB",
          700: "#1D4ED8",
          800: "#1E40AF",
          900: "#1E3A8A",
        },
        gray: {
          50: "#F5F5F5",
          100: "#E5E5E5",
          200: "#D4D4D4",
          300: "#A3A3A3",
          400: "#888888",
          500: "#737373",
          600: "#525252",
          700: "#404040",
          800: "#1A1A1A",
          900: "#0A0A0A",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        "lift": "0 28px 60px -28px rgba(0,0,0,0.85)",
        "lift-light": "0 28px 60px -30px rgba(20,30,80,0.35)",
        "glow-red": "0 18px 50px -20px rgba(229,50,45,0.55)",
        "glow-blue": "0 18px 50px -20px rgba(47,107,255,0.55)",
      },
      backgroundImage: {
        "grad-red": "linear-gradient(125deg, #ff706b 0%, #ff0800 52%, #940500 100%)",
        "grad-red-soft": "linear-gradient(125deg, #ff8480 0%, #ff211a 100%)",
        "grad-blue": "linear-gradient(125deg, #9bb7ff 0%, #5283ff 52%, #304c94 100%)",
        "grad-blue-soft": "linear-gradient(125deg, #a9c1ff 0%, #638fff 100%)",
        "grad-brand": "linear-gradient(90deg, #ff0800 0%, #4a76e6 100%)",
      },
      maxWidth: {
        "screen-2xl": "1320px",
      },
      transitionDuration: {
        400: "400ms",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}